<?php //@ARGS _content, context, assetRoot ?>
<section id="portfolio">
  <a href="/portfolio/mli">
    <article>
      <img src="/assets/portfolio/mli/michelin-button.png" class="portfolio-card-bg" />
      <div class="overlay"></div>
      <div class="portfolio-card-content">
        <h3>Michelin Learning Institute</h3>
        <p>Learning platform for tire dealers worldwide</p>
      </div>
    </article>
  </a>
  <a href="/portfolio/smart-coasters">
    <article>
      <img src="/assets/portfolio/smart-coaster/thumbnail.jpg" class="portfolio-card-bg" />
      <div class="overlay"></div>
      <div class="portfolio-card-content">
        <h3>Smart Coasters</h3>
        <p>How popular is your drink?</p>
      </div>
    </article>
  </a>
</section>