<?php //@ARGS _content, context, title ?>
<portfolio-piece>
	<hero-img>
		<img src="/assets/media/images/portfolio/integer-2017-holiday.jpg" alt="">
	</hero-img>
	<section class="overview">
		<grid-cell>
			<content-wrapper>
				<h1>Integer's 2017 Digital Holiday Card</h1>
				<span class="subline">Leaving last year's card in the dust!</span>
			</content-wrapper>
		</grid-cell>
	</section>
	<section class="context">

	</section>
	<section class="challenges">

	</section>
	<section class="process">

	</section>
	<section class="solution">

	</section>
	<section class="results">

	</section>
</portfolio-piece>