<?php //@ARGS _content, context, title ?>
<section id="portfolio-intro">
	<h1>Michelin Learning Institute</h1>
	<span class="descriptor">Learning platform for Michelin tire dealers</span>
	<img src="/assets/portfolio/mli/mli-both.png" />
</section>
<section id="portfolio-basics" class="portfolio">
	<h2>The Basics</h2>
	<div>
		<strong>Company</strong>
		<span>Michelin</span>
	</div>
	<div>
		<strong>Team</strong>
		<span>Dealer Training</span>
	</div>
	<div>
		<strong>Timeframe</strong>
		<span>Ongoing</span>
	</div>
	<div>
		<strong>My Role</strong>
		<span>Web Developer</span>
	</div>
	<div>
		<strong>Website</strong>
		<a href="https://michelinlearninginstitute.net/">michelinlearninginstitute.net</a>
</section>
<section id="the-deliverables" class="portfolio text-column">
	<h2>The Deliverables</h2>
	<ul>
		<li>
			A custom Learning Management System complete with courses, quizzes, industry news and gamification features.
		</li>
		<li>
			Full site analytics including course completions and other learning metrics.
		</li>
		<li>
			Report generation and export to external systems for use in compensation and vendor LMS compatibilities.
		</li>
		<li>
			Eventual integration into Salesforce.
		</li>
	</ul>
</section>
<section id="the-client" class="portfolio text-column">
	<h2>The Client</h2>
	<img class="center" src="/assets/portfolio/mli/michelin_man.jpg" />
	<span>Michelin</span>
	<p>Michelin is an international tire empire. From passenger and light trucks to agriculture, they have a line for all seasons and work needs.</p>
</section>
<section id="the-goals" class="portfolio text-column">
	<h2>The Goals</h2>
	<p>
		Michelin recognized the need for an extensive training program in North America as far back as the 60's. To best drive sales, they sought to educate their dealers in the art of sales and business. Around 2014, they tapped The Integer Group to reinvigorate their e-learning platform, started around 2001, for the 21st century.
	</p>
	<p>The platform should be able to:</p>
	<ul>
		<li>
			The platform should be able to host a variety of courses on tire lines such as the Defender T+H and Pilot Sport 4 S in addition to useful small business skills such as telephone speaking skills and using the warranty application to submit claims
		</li>
		<li>
			Contain downloadable resources such as articles, brochures and promotional materials
		</li>
		<li>
			Run promotions every few months with an incentive ranging from pre-loaded gas giftcards to Michelin branded tire gauges
		</li>
		<li>
			Generate custom reports for program administrators to use in determining bonuses, goal attainment and insights into effectiveness of training materials on store performance
		</li>
		<li>
			Google Analytics covering every inch of the site with metadata embedded into links
		</li>
	</ul>
</section>
<section id="the-challenges" class="portfolio text-column">
	<h2>The Challenges</h2>
	<p>Joining in 2016, my tasks revolved around cleaning up the codebase, applying fixes, adding new courses and promotional materials. I eventually became the main system administrator for the site.</p>
	<p>Three major challenges occurred with this project: Scaling the reporting functionality. Introducing complex gamification/promotional features. Integrating into Salesforce.</p>
	<h3>Scaling the reporting functionality</h3>
	<p>
		The underlying structure for the courses worked pretty well for the first few years of MLI's life. The performance it had started to degrade as new requirements were introduced. When a new SCORM package vendor was introduced, a few new courses would have the lesson and the exam component combined into a single package. Originally, exams were maintained as a separate entity for reporting purposes, this was no longer possible with the new courses. At the time, the reports had their queries modified to accommodate this.
	</p>
	<p>
		As time went on and new courses were introduced, we realized that the queries no longer had the performance it needed in order to accommodate running through the front-end of the site for the managers. Understandably, this caused some frustration and requests had to be routed through us in order to run these reports. We performed some analysis and determined with the number of courses and data structure, the reports were now taking about 20 minutes to complete, well past Apache's timeout limit. It also had few holes for the new courses. Upon evaluation of the managers' reporting usage I put forth the proposal to convert the query into an once-nightly cron-job containing a rolling set of the last two years of completion data.
	</p>
	<p>
		This change accomplished two things. One, it drastically reduced the load on the server allowing us to reduce the number of scalers we needed to serve the site. Two, by converting the front-end query to a simple view of this rolling set, we were able to take average query times from 20 minutes to 20 seconds. As we made the changes, I consulted with our DBA to come up with an optimization plan which reduced the cost in time and server resources for the nightly script by approximately 30%.
	</p>
	<h3>Introducing complex gamification/promotional features</h3>
	<p>
		With the new course types came new types of promotions. The typical promotion is "complete this course and receive this item". We were now getting requests to add surveys and multiple course completions for tiered rewards. This necessitated some cleaning up of the current promotional logic. Originally, we would spend between 20-40 hours on implementing a new promotion due to manual hand coding of display and business logic. With revisions to the underlying code, I was able to reduce this time by half and reduce subsequent QA needs. Additionally, promotions in the past had to be carefully monitored in order to not exceed incentive stocks and turned off by hand. Automated event deployment and revocation were added in this update allowing us to reduce our inventory buffer from around 300 pieces to 50.
	</p>
	<h3>Integrating into Salesforce</h3>
	<p>
		Michelin, towards the beginning of 2018, determined that they needed to start transitioning all of their training vendors and dealers onto Salesforce for a portal experience, connecting all of the systems together. The timeline on this was approximately three months. Due to the various updates made to MLI in 2016-2018, full Salesforce integration was acheived within two weeks. The next nearest vendor was around two months past the deadline. A great deal of effort was put into isolating major components such as authentication from the other functionality under my guidance was a large enabler of this success.
	</p>
</section>
<section id="the-results" class="portfolio text-column">
	<h2>The Results</h2>
	<p>
		Michelin Learning Institute now boasts several thousand visitors per day and hundreds of dealers per second during promotional periods. With this level of traffic, we collect close to 20,000 tracking events per day. The site is now running on one Rackspace instance instead of two. Average time to first byte decreased from 2-3 seconds to 200-400ms.
	</p>
</section>