<?php //@ARGS _content, context, assetRoot, title ?>
<html>
	<head>
		<meta charset="utf-8">
  		<meta http-equiv="X-UA-Compatible" content="IE=edge">
  		<meta name='viewport' content='width=device-width, initial-scale=1.0' />
		<title>{==$title=}</title>
		<meta name="description" content="John Purtle creates blazing fast, reliable and responsive websites or applications for those who wants their business to stand out.">
		<link rel="stylesheet" type="text/css" href="assets/css/style.css">
		<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png?v=2">
		<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png?v=2">
		<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png?v=2">
		<link rel="icon" href="/favicon.ico?v=2" />
		<link rel="manifest" href="/manifest.json">
		<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
		<meta name="theme-color" content="#ffffff">
	</head>
	<body>
		{==$_content=}
		<script src="assets/js/main-min.js"></script>
	</body>
</html>