<?php //@ARGS _content, context, assetRoot, title ?>
<html>
	<head>
		<meta charset="utf-8">
  		<meta http-equiv="X-UA-Compatible" content="IE=edge">
  		<meta name='viewport' content='width=device-width, initial-scale=1.0' />
		<title>{==$title=}</title>
		<meta name="description" content="John Purtle creates blazing fast, reliable and responsive websites or applications for those who wants their business to stand out.">
		<link rel="stylesheet" type="text/css" href="/assets/css/style.css?v=2">
		<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png?v=3">
		<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png?v=3">
		<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png?v=3">
		<link rel="manifest" href="/site.webmanifest">
		<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
		<meta name="msapplication-TileColor" content="#da532c">
		<meta name="theme-color" content="#ffffff">

		<!-- Global site tag (gtag.js) - Google Analytics -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=UA-131203684-1"></script>
		<script>
		  window.dataLayer = window.dataLayer || [];
		  function gtag(){dataLayer.push(arguments);}
		  gtag('js', new Date());

		  gtag('config', 'UA-131203684-1');
		</script>

	</head>
	<body>
		<header>
			<grid-cell class="brown">
				<a href="/" class="site-logo">
					<img src="/assets/media/images/JP-Logo-Final-Blue.png" />
				</a>
				<nav>
					<a href="/portfolio">Portfolio</a>
					<a href="/assets/pdf/jpurtleresumeJ192022.pdf" target="_blank">Resume</a>
					<a href="/about">About</a>
					<a href="/contact">Contact</a>
				</nav>
			</grid-cell>
		</header>
		<main>
			{==$_content=}
		</main>
		<footer>
			<grid-cell class="grid-cell lightblue">
				<span class="copyright">&copy; John Purtle <?php echo date('Y'); ?></span>
			</grid-cell>
		</footer>
		<script src="/assets/js/main.js"></script>
	</body>
</html>