<?php //@ARGS _content, context, assetRoot, title ?>
<about-me>
  <grid-cell class="lightblue">
    <content-wrapper>
      <h1>
        Github
      </h1>
      <h2>Magnus - Current Project</h2>
      <p>
        Magnus has been an ongoing project through about four iterations on paper and in digital form. Magnus is a response to the state of PHP development. I find many PHP frameworks to be conceptually good but lacking, execution wise.
      </p>
      <p>
        My goal is to develop a strong PHP framework with well written documentation and proper application of limited scope. Far too often, if there's an issue in the framework I'm working in, I'll have to unravel about twenty layers of stack traces before I can actually find the issue at hand. At the same time, hidden dependencies appear all over the place. I wish that if I'm adding a new route to a website or application, the scope of an error would always be limited to the routing mechanism, not five other places in the codebase.
      </p>
      <a href="https://github.com/jmpurtle/Magnus/tree/development" target="_blank">Magnus</a>
    </content-wrapper>
    </grid-cell>
    <grid-cell class="brown">
    <content-wrapper>
      <h2>Moby Dick</h2>
      <p>
        To learn a little about Vue, I created a fairly simple application using it as a client-side framework.
      </p>
      <a href="https://github.com/jmpurtle/moby-dick-project" target="_blank">Moby Dick</a>
    </content-wrapper>
  </grid-cell>
</about-me>