<?php //@ARGS _content, context, title ?>
<thanks-message>
  <grid-cell class="brown">
    <content-wrapper>
      <p>Thanks! I'll be in touch within two business days.</p>
    </content-wrapper>
  </grid-cell>
</thanks-message>
<get-in-touch>
  <grid-cell class="lightblue one-half">
    <content-wrapper>
      <p>Hello! Thanks for your interest in working together.</p>

      <p>The best sites are the ones with value for both the visitor and the business. I’d love to hear about your responsive web or shopper journey design project. If it’s about getting the right information to the right person at the right time, I’m your guy. I focus primarily on analytics informed website designs, builds and physical analytics products, built with care and precision.</p>

      <p>I’m not always able to respond to every email that comes my way but if it sounds like a good fit, I’ll get back to you within two business days.</p>

      <p>If you have a general question or invitation to attend/speak, feel free to send me an email at hello@johnpurtle.com.</p>

      <p>Rather meet me in person? Email me and ask, whether it's my views on the industry, shooting the breeze or about a project!</p>
    </content-wrapper>
  </grid-cell>
  <grid-cell class="brown one-half">
    <content-wrapper>
      <a href="#" id="contact-form"></a>
      <h2>How can I help?</h2>
      <form action="/contact/lead" method="post">
        <label class="one-half">NAME <input type="text" name="name" /></label>
        <label class="one-half">ORGANIZATION <input type="text" name="org" /></label>
        <label>EMAIL ADDRESS <input type="text" name="email" required /></label>
        <label>PROJECT DESCRIPTION <textarea name="project"></textarea></label>
        <label class="one-half">BUDGET <input type="text" name="budget" /></label>
        <label class="one-half">LAUNCH DATE <input type="text" name="launchdate" /></label>
        <label>HOW DID YOU FIND ME? <input type="text" name="referral" /></label>
        <button class="cta blue-on-white">Let's chat</button>
      </form>
    </content-wrapper>
  </grid-cell>
</get-in-touch>