<?php //@ARGS _content, context, assetRoot, title ?>
<about-me>
  <grid-cell class="lightblue">
    <content-wrapper>
      <h1>
        FULL STACK DEVELOPER, MARKETER AND SERIAL HOBBYIST
      </h1>
      <h2>About John</h2>
      <p>
        Growing up, I've been known as a serial dabbler. Like a butterfly, I would flit from one hobby to another in pursuit of the interesting. Glassblowing, blacksmithing, woodworking, creating minefields out of scattered Legos. You name it, I may have already tried it.
      </p>
      <p>
        I got into software development around 2014 and fell in love since. I began working, nestled in a small room with no windows, at corporate and wondered if there was something better. I then joined <a href="https://integer.com" target="_blank">The Integer Group</a> as a Web Developer. Not too long after I began, I took on more responsibility as the technical advisory and "Chief Executive of Awesome Sh!t". I advised clients on their digital projects and tinkered with technology for marketing use.
      </p>
      <p>
        My next step in this grand journey called Life took me to <a href="https://www.obicreative.com/" target="_blank">OBI&nbsp;Creative</a>. A research, strategy and advertising agency. While my work was primarily in Drupal, I learned quite a bit about understanding your customers, employees and business needs, a critical component in rebranding efforts and new initiatives. I witnessed the transformation of an aging and out of touch business into a fresh and modern brand serving its customer with a ferocity unheard of in the insurance industry.
      </p>
      <p>
        These past few years had me visiting several different companies on a consulting basis such as <a href="https://shazam.net" target="_blank">Shazam</a>. Now I'm currently working for Wells Fargo, intially as a CX Interaction Designer before combining my engineering skills to become their first UX Engineer. I learned a lot about the financial services sector and took on various leadership roles due to my unique experience.
      </p>
      <p>
        Yes, being a UX Engineer comes with many responsibilities such as working with executives, business stakeholders, and scrum teams to provide the right solution for the right problems at the right times. I took charge of various efforts including Americans with Disabilities Act Title 1 Compliance, developing roles and procedures for teams, and constructing a design system that supports over 80 different teams.
      </p>
      <blockquote>
        Optimization without measurement is by definition, premature. <span class="author">&mdash; Unknown</span>
      </blockquote>
      <p>
        Over the years, I've found that the best user experiences are the ones coming from rigorously reviewed requirements and consistently applied design principles. Without measurement, it's hard to tell if something is a true problem. That's why I strive to have data for quality decisions while improving user experience.
      </p>
      <p>
        I use my experiences across companies, industries, and project types to give you the right solution and iterate quickly upon it for more efficient projects and straightforward user experiences.
      </p>
    </content-wrapper>
  </grid-cell>
</about-me>