<?php //@ARGS _content, context, assetRoot, title ?>
<about-me>
  <grid-cell class="lightblue">
    <content-wrapper>
      <h1>
        FULL STACK DEVELOPER, MARKETER AND SERIAL HOBBYIST
      </h1>
      <h2>About John</h2>
      <p>
        Growing up, I've been known as a serial dabbler. Like a butterfly, I would flit from one hobby to another in pursuit of the interesting. Glassblowing, blacksmithing, woodworking, creating minefields out of scattered Legos. You name it, I may have already tried it.
      </p>
      <p>
        I got into software development around 2014 and fell in love since. I began working, nestled in a small room with no windows, at corporate and wondered if there was something better. I then joined <a href="https://integer.com" target="_blank">The Integer Group</a> as a Web Developer. Not too long after I began, I took on more responsibility as the technical advisory and "Chief Executive of Awesome Sh!t". I advised clients on their digital projects and tinkered with technology for marketing use.
      </p>
      <p>
        My next step in this grand journey called Life took me to <a href="https://www.obicreative.com/" target="_blank">OBI&nbsp;Creative</a>. A research, strategy and advertising agency. While my work was primarily in Drupal, I learned quite a bit about understanding your customers, employees and business needs, a critical component in rebranding efforts and new initiatives. I witnessed the transformation of an aging and out of touch business into a fresh and modern brand serving its customer with a ferocity unheard of in the insurance industry.
      </p>
      <blockquote>
        Optimization without measurement is by definition, premature. <span class="author">&mdash; Unknown</span>
      </blockquote>
      <p>
        In my research, I've found that there's a goldmine of data in the most unsuspecting places. Virtual and Augmented reality can give you data about visual engagement with your brands. You can predict inventory shortages in areas based on the weather. You can track how much people might like the taste of a particular beer by using a Raspberry Pi powered beer float and measuring the change in volume over time.
      </p>
      <p>
        Much of this data goes untapped and I leverage my background in marketing and business to capture the data and turn it into actionable insights for you.
      </p>
    </content-wrapper>
  </grid-cell>
</about-me>