<?php //@ARGS _content, context, assetRoot ?>
<recent-works>
  <grid-cell class="lightblue">
    <portfolio-gallery>
      <portfolio-summary class="one-half">
        <portfolio-bg>
          <img src="/assets/media/images/portfolio/plac-portfolio.jpg" alt="">
        </portfolio-bg>
        <article>
          <h2>Pearson Lakes Art Center</h2>
          <p>Website refresh</p>
          <a href="#">Case Study coming soon! ></a>
        </article>
      </portfolio-summary>
      <portfolio-summary class="one-half">
        <portfolio-bg>
          <img src="/assets/media/images/portfolio/lughlms-portfolio.jpg" alt="">
        </portfolio-bg>
        <article>
          <h2>LughLMS</h2>
          <p>Landing page for a data driven Learning Management System</p>
          <a href="#">Case Study coming soon! ></a>
        </article>
      </portfolio-summary>
      <portfolio-summary class="one-half">
        <portfolio-bg>
          <img src="/assets/media/images/portfolio/michelin-portfolio.jpg" alt="">
        </portfolio-bg>
        <article>
          <h2>Michelin Learning Institute</h2>
          <p>Learning platform for tire dealers</p>
          <a href="#">Case Study coming soon! ></a>
        </article>
      </portfolio-summary>
      <portfolio-summary class="one-half">
        <portfolio-bg>
          <img src="/assets/media/images/portfolio/integer-2017-holiday.jpg" alt="">
        </portfolio-bg>
        <article>
          <h2>Integer's 2017 Holiday Site</h2>
          <p>A recounting of significant events in 2017</p>
          <a href="#">Case Study coming soon! ></a>
        </article>
      </portfolio-summary>
    </portfolio-gallery>
  </grid-cell>
</recent-works>