<?php //@ARGS _content, context, title ?>
<project-overview>
	<grid-cell class="brown">
		<content-wrapper>
			<h1>Pearson Lakes Art Center Website Refresh</h1>
			<p>Pearson Lakes Art Center is an art center based in Okoboji, founded in 1991. The center is an art museum, learning center, theater and studio for visitors and artists alike.</p>
		</content-wrapper>
	</grid-cell>
</project-overview>
<project-flow>
	<grid-cell>
		<img src="/assets/media/images/portfolio/plac-flow.jpg" />
		<small>Getting some details down about what was needed on the site</small>
		<p>Some discussion about the global site flow</p>
	</grid-cell>
</project-flow>
<project-wireframes>
	<grid-cell>
		<img src="/assets/media/images/portfolio/plac-wireframes.jpg" />
		<p>Some discussion about the wireframing process</p>
	</grid-cell>
</project-wireframes>
<project-palette>
	<grid-cell>
		<p>Display typography and color palette</p>
	</grid-cell>
</project-palette>
<project-screens>
	<grid-cell>
		<p>Display screenshots related to the project</p>
	</grid-cell>
</project-screens>