<?php //@ARGS _content, context, title ?>
<article class="portfolio-piece">
	<section class="header">
		<span class="portfolio-piece-type concept">Concept</span>
		<h1>Smart Drink Coasters</h1>
	</section>
	<section class="body portfolio text-column">
		<div class="portfolio-image">
			<figure>
				<img src="/assets/portfolio/smart-coaster/coaster-row.jpg" />
			</figure>
			<figcaption>
				Could you measure how much someone likes a drink based on the glass's weight over time?
			</figcaption>
		</div>
		<p>
			Did you know that most bars only keep a few kegs on hand and rely on their vendors to replace them on demand? Turns out a few savvy bars are making use of weight sensors to measure the weight of the kegs over the course of the night and once those kegs dip below a critical level, an alert is sent out to the vendor to deliver more keeping the business and its patrons happy.
		</p>
		<p>
			But is that all we can do with it? I think we could absolutely go further. What if we took similar weight measure technology and applied it to coasters? You could measure a few things like the amount of "hand time" each drink got along with the rate of consumption. Add a digital code to each coaster so people could look up more information about their drink and you've got a pretty powerful tool for marketing and logistics.
		</p>
		<div class="portfolio-image">
			<figure>
				<img src="/assets/portfolio/smart-coaster/hand-time.jpg" />
			</figure>
			<figcaption>
				Is the latest beer a hit or a miss?
			</figcaption>
		</div>
		<p>
			Consider this: You're rolling out a new beer and you're wondering if your customers like it. Surely you'll measure the keg throughout the night and see if there's high demand for it? There's something missing, what if your high demand is actually just good copy and photos from the menu or waiter suggestions getting people to order the drink but then they only take a few sips of it then push it aside because it didn't hit the right notes? You wouldn't get that kind of information from weighing the kegs.
		</p>
	</section>
	<section class="cta">
		<p>
			Interested in trying this idea out?<br/><a href="mailto:hello@johnpurtle.com">Get in touch.</a>
		</p>
	</section>
	<section class="footer">
		<ul class="tags">
			<li>
				<img class="tagicon" src="/assets/media/images/tagicon.svg" /><a href="/portfolio?tag=concept">Concept</a>
			</li>
		</ul>
	</section>
</article>