<?php //@ARGS _content, context, title ?>
<intro-hero>
  <grid-cell class="brown">
    <content-wrapper>
      <h1>UX Designer, Programmer, Analyst</h1>
      <autotyper-section>
        <span>John Purtle creates</span>
        <autotyper-container>
          <span id="autotype" data-to-type='[" actionable analytics.", " delightful designs.", " glistening glass.", " metal marvels.", " wonderful websites."]' aria-hidden="true"> </span>
        </autotyper-container>
      </autotyper-section>
      <a href="#contact-form" class="cta blue-on-white">Let's chat</a>
    </content-wrapper>
  </grid-cell>
</intro-hero>
<latest-post>
  <grid-cell class="brown one-third overlay-wrapper mob-hide">
    <color-overlay></color-overlay>
  </grid-cell>
  <grid-cell class="lightblue two-third content">
    <content-wrapper>
      <span>LATEST POST</span>
      <article>
        <h2>Web Laboratory: Observing Mutations</h2>
        <p>"It's alive!" exclaims the developer as he labors in his laboratory, making use of the MutationObserver Web API on his website. What could he possibly be using it for..?</p>
        <a href="/news/web-lab-mutation-observer">Read more ></a>
      </article>
    </content-wrapper>
  </grid-cell>
</latest-post>
<recent-works>
  <grid-cell class="lightblue">
    <portfolio-gallery>
      <portfolio-summary class="one-half">
        <portfolio-bg>
          <img src="/assets/media/images/portfolio/plac-portfolio.jpg" alt="">
        </portfolio-bg>
        <article>
          <h2>Pearson Lakes Art Center</h2>
          <p>Website refresh</p>
          <a href="#">Case study coming soon ></a>
        </article>
      </portfolio-summary>
      <portfolio-summary class="one-half">
        <portfolio-bg>
          <img src="/assets/media/images/portfolio/lughlms-portfolio.jpg" alt="">
        </portfolio-bg>
        <article>
          <h2>LughLMS</h2>
          <p>Landing page for a data driven Learning Management System</p>
          <a href="#">Case study coming soon ></a>
        </article>
      </portfolio-summary>
      <portfolio-summary class="one-half">
        <portfolio-bg>
          <img src="/assets/media/images/portfolio/michelin-portfolio.jpg" alt="">
        </portfolio-bg>
        <article>
          <h2>Michelin Learning Institute</h2>
          <p>Learning platform for tire dealers</p>
          <a href="#">Case study coming soon ></a>
        </article>
      </portfolio-summary>
      <portfolio-summary class="one-half">
        <portfolio-bg>
          <img src="/assets/media/images/portfolio/integer-2017-holiday.jpg" alt="">
        </portfolio-bg>
        <article>
          <h2>Integer's 2017 Holiday Site</h2>
          <p>A recounting of significant events in 2017</p>
          <a href="#">Case Study coming soon! ></a>
        </article>
      </portfolio-summary>
    </portfolio-gallery>
  </grid-cell>
</recent-works>
<get-in-touch>
  <grid-cell class="lightblue one-half">
    <content-wrapper>
      <p>Hello! Thanks for your interest in working together.</p>

      <p>The best sites are the ones with value for both the visitor and the business. I’d love to hear about your responsive web or shopper journey design project. If it’s about getting the right information to the right person at the right time, I’m your guy. I focus primarily on analytics informed website designs, builds and physical analytics products, built with care and precision.</p>

      <p>I’m not always able to respond to every email that comes my way but if it sounds like a good fit, I’ll get back to you within two business days.</p>

      <p>If you have a general question or invitation to attend/speak, feel free to send me an email at hello@johnpurtle.com.</p>

      <p>Rather meet me in person? Email me and ask, whether it's my views on the industry, shooting the breeze or about a project!</p>
    </content-wrapper>
  </grid-cell>
  <grid-cell class="brown one-half">
    <content-wrapper>
      <a href="#" id="contact-form"></a>
      <h2>How can I help?</h2>
      <form action="/contact/lead" method="post">
        <label class="one-half">NAME <input type="text" name="name" /></label>
        <label class="one-half">ORGANIZATION <input type="text" name="org" /></label>
        <label>EMAIL ADDRESS <input type="text" name="email" required /></label>
        <label>PROJECT DESCRIPTION <textarea name="project"></textarea></label>
        <label class="one-half">BUDGET <input type="text" name="budget" /></label>
        <label class="one-half">LAUNCH DATE <input type="text" name="launchdate" /></label>
        <label>HOW DID YOU FIND ME? <input type="text" name="referral" /></label>
        <button class="cta blue-on-white">Let's chat</button>
      </form>
    </content-wrapper>
  </grid-cell>
</get-in-touch>