<?php //@ARGS _content, context, title ?>
<header class="fixed-header">
  <nav>
    <div class="nav-header">
      <div class="nav-title">
        <a href="/">
          <div></div>
        </a>
      </div>
    </div>
    <div class="nav-btn">
      <label for="nav-check">
        <span></span>
        <span></span>
        <span></span>
      </label>
    </div>
    <input type="checkbox" id="nav-check">
    <div class="nav-links">
      <a href="/portfolio">Portfolio</a>
      <a href="/contact">Contact</a>
      <a href="/about">About</a>
      <a href="/assets/pdf/jpurtleresume2018.pdf" target="_blank">Resume</a>
    </div>
  </nav>
</header>
<section id="hero" class="bubble-hero">
  <img src="/assets/media/images/jpheadshot.jpg" alt="John Purtle">
</section>
<main>
  
  <section id="services">
    <div>
      <div class="one-half">
        <div class="service-header">
          <img src="/assets/media/images/development-icon.png" alt="Development">
        </div>
        <dt>Development</dt>
        <dd>
          I create fast and responsive sites to drive conversions and increase sales, harnessing the power of a streamlined, custom framework.
        </dd>
      </div><div class="one-half">
        <div class="service-header">
          <img src="/assets/media/images/marketing-icon.png" alt="Marketing">
        </div>
        <dt>Marketing</dt>
        <dd>
          I will help you design effective email campaigns, sales funnels and microsites, by applying an understanding of your business and its current marketing channels.
        </dd>
      </div><div class="one-half">
        <div class="service-header">
          <img src="/assets/media/images/ux-icon.png" alt="User Interface and Experience Design">
        </div>
        <dt>UI/UX</dt>
        <dd>
          Identify and remove barriers in your shopper's journey for greater customer satisfaction with an in-depth audit.
        </dd>
      </div><div class="one-half">
        <div class="service-header">
          <img src="/assets/media/images/data-icon.png" alt="Data">
        </div>
        <dt>Data</dt>
        <dd>
          Get on the road to success with actionable insights, business analysis and integration assistance for your business
        </dd>
      </div>
    </div>
  </section>
  <section id="portfolio-highlights">
    Highlights of the portfolio content here
  </section>
</main>
<footer>
  Footer content
</footer>