<?php //@ARGS _content, context, title ?>
<section id="keyPoints">
  <span>Nimble websites</span>
  <span>Effective marketing</span>
  <span>Streamlined user experience</span>
  <span>Actionable analytics</span>
  <span>John Purtle</span>
</section>
<section id="portfolio">
  <a href="/portfolio/mli">
    <article>
      <img src="/assets/portfolio/mli/michelin-button.png" class="portfolio-card-bg" />
      <div class="overlay"></div>
      <div class="portfolio-card-content">
        <h3>Michelin Learning Institute</h3>
        <p>Learning platform for tire dealers worldwide</p>
      </div>
    </article>
  </a>
</section>
<section id="invite-to-contact">
  <h3>Interested in working with me?</h3>
  <p>Contact me by <a href="mailto:hello@johnpurtle.com">email</a>,</p>
</section>